# -*- coding: utf-8 -*-
"""Парсинг вакансий аналитика с hh.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rb16yeMAOMBc3U_e1Aq1aAJfx0U9HYUB
"""

import requests
from pprint import pprint

name_msk = []
sal_msk = []
for i in range(20):
  if len(name_msk) < 100:
    url = f'https://api.hh.ru/vacancies?text=Аналитик&search_field=name&only_with_salary=True&area=1&per_page=100&page={str(i)}'
    items = requests.get(url).json()['items']
    for item in items:
      if item['salary']['from'] is not None and len(name_msk) < 100:
        name_msk.append(item['name'])
        sal_msk.append(item['salary'])
  else:
    break

name_spb = []
sal_spb = []
i = 0
while len(name_spb) < 100:
  url = f'https://api.hh.ru/vacancies?text=Аналитик&search_field=name&only_with_salary=True&area=2&per_page=100&page={str(i)}'
  items = requests.get(url).json()['items']
  for item in items:
    if item['salary']['from'] is not None and len(name_spb) < 100:
      name_spb.append(item['name'])
      sal_spb.append(item['salary'])
  i += 1

url1 = 'https://www.cbr-xml-daily.ru/daily_json.js'
data_val = requests.get(url1).json()
sal_msk_clear = []
sal_spb_clear = []
cities = [sal_msk, sal_spb]
for city in cities:
  for sal in city:
      if sal['currency'] == 'RUR':
        coef = 1
      elif sal['currency'] == 'BYR':
        coef = data_val['Valute']['BYN']['Value'] / data_val['Valute']['BYN']['Nominal']
      else:
        coef = data_val['Valute'][sal['currency']]['Value'] / data_val['Valute'][sal['currency']]['Nominal']
      if sal['gross']:
        gross = 1
      else:
        gross = 0.87
      if city == sal_msk:
        sal_msk_clear.append(int(sal['from']*coef*gross))
      else:
        sal_spb_clear.append(int(sal['from']*coef*gross))

spb_inters = sorted([(x,sal_spb_clear[i]) for i, x in enumerate(name_spb) if x in name_msk], key=lambda x: x[1])[::-1]

msk_inters = sorted([(x,sal_msk_clear[i]) for i, x in enumerate(name_msk) if x in name_spb], key=lambda x: x[1])[::-1]

spb_uniq = {}
for item in spb_inters:
  if item[0] not in spb_uniq.keys():
    spb_uniq[item[0]] = item[1]

msk_uniq = {}
for item in msk_inters:
  if item[0] not in msk_uniq.keys():
    msk_uniq[item[0]] = item[1]

vacancies = []
for key1, value1 in spb_uniq.items():
  for key2, value2 in msk_uniq.items():
    if key1 == key2 and value1 > value2:
      vacancies.append(key1)

if len(vacancies) != 0:
  print(f'Длина списка вакансий: {len(vacancies)}\nСамая высокооплачиваемая вакансия: {vacancies[0]} - {spb_uniq[vacancies[0]]} руб.')
else:
  print('Вакансий не найдено')